@echo off
echo Iniciando TM Gerador VBA...
echo Instalando dependencias se necessario...
pip install -r requirements.txt > nul 2>&1

echo Iniciando o Servidor de Backend...
start cmd /k "python server.py"

echo Abrindo Interface Grafica (Word Macro Engine)...
timeout /t 2 > nul
start index.html
